# Generated by scripts/gen_models.sh from backend/api/serp-api.yaml. Do not edit by hand.

from __future__ import annotations

from typing import Annotated, Any, Literal
from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from uuid import UUID


class Account(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    balance: float
    """
    Negative after a refund of credits that were already spent; requests then get 402 insufficient_credits
    """
    rate_limit_rps: int
    plan: str
    key: Key | None = None
    monthly_spend_cap: float | None = None
    month: Month


class AnswerBox(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    title: str | None = None
    answer: str | None = None
    snippet: str | None = None
    snippet_highlighted: list[str] | None = None
    link: str | None = None


class AutocompleteResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    results: list[Suggestion]
    meta: Meta


class Batch(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: UUID
    status: str
    endpoint: Annotated[str, Field(examples=["/v1/search"])]
    created_at: AwareDatetime
    completed_at: AwareDatetime | None = None
    credits_used: float | None = None
    poll_url: str
    webhook_url: str | None = None
    webhook_status: str | None = None
    error: Error2 | None = None
    result: dict[str, Any] | None = None
    """
    Present when done; kept 24h. The endpoint's response body, or {markdown, meta} for format=markdown jobs
    """


class BatchCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    endpoint: str
    requests: Annotated[list[dict[str, Any]], Field(max_length=100, min_length=1)]
    """
    Request bodies for `endpoint` (same fields as the realtime endpoint)
    """
    webhook_url: AnyUrl | None = None
    """
    POSTed each job's result, always signed with X-SerpKite-Signature (v1=hex HMAC-SHA256 of `<timestamp>.<body>` with the account webhook secret; see createBatches). Defaults to the account webhook
    """


class BatchCreateResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    batches: list[Batch | Error]


class CSEResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    kind: Literal["customsearch#search"]
    url: dict[str, Any] | None = None
    queries: dict[str, Any] | None = None
    context: dict[str, Any] | None = None
    searchInformation: SearchInformation
    items: list[Item]


class Endpoint(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    endpoint: str
    requests: int
    success_rate: float
    """
    Share of requests without a 5xx (0-1)
    """
    p50_ms: int
    p95_ms: int


class EngineParam1(RootModel[list[str]]):
    root: Annotated[list[str], Field(min_length=1)]
    """
    Which search providers may answer. `google` (the default) is Google only; within Google, SerpKite always fails over across its own proxy pools. `auto` allows falling back to other enabled providers, in route order, when Google is blocked or times out. A single other provider (`brave`) or a list (`["google","brave"]`, or `google,brave` in a query string) restricts the request to those providers. `meta.engine` always names the provider that answered and credits follow that provider's price. A key with "Allow fallback to other search engines" on treats a request without `engine` as `auto`. `consensus` (`/v1/search` only; 400 elsewhere, and it can't be combined with other names) queries several independent search indexes in parallel (at most one Bing-backed provider, so Yahoo or DuckDuckGo never count as agreeing with Bing), merges the results by URL and ranks them by how many providers returned each one. Each result lists its `sources`; `meta.engine` is `consensus` and `meta.route` lists every provider attempt. It stops once `num` unique results are in hand or after a few seconds, and costs the sum of one page at each provider that returned results (providers that failed, came back empty or were never started are free).
    """


class Error(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    error: Error1


class Error1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: Annotated[
        str,
        Field(
            examples=[
                "unauthorized",
                "invalid_request",
                "insufficient_credits",
                "rate_limited",
                "daily_limit_reached",
                "spend_cap_reached",
                "key_limit_reached",
                "idempotency_key_reused",
                "forbidden",
                "not_found",
                "upstream_error",
                "upstream_blocked",
                "upstream_timeout",
                "unavailable",
                "internal",
            ]
        ),
    ]
    """
    403: spend_cap_reached, key_limit_reached, forbidden. 409/422: idempotency_key_reused. 429: rate_limited, daily_limit_reached. 503: upstream_error, upstream_blocked, upstream_timeout, unavailable (the API never sends 502 or 504)
    """
    message: str
    request_id: str | None = None


class Error2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: str | None = None
    message: str | None = None


class ImageResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    position: int
    title: str
    image_url: str
    image_width: int | None = None
    image_height: int | None = None
    thumbnail_url: str | None = None
    source: str | None = None
    domain: str | None = None
    link: str | None = None


class ImagesResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    results: list[ImageResult]
    meta: Meta


class Item(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    kind: Literal["customsearch#result"] | None = None
    title: str | None = None
    htmlTitle: str | None = None
    link: str | None = None
    displayLink: str | None = None
    snippet: str | None = None
    htmlSnippet: str | None = None
    formattedUrl: str | None = None
    htmlFormattedUrl: str | None = None
    pagemap: dict[str, Any] | None = None
    image: dict[str, Any] | None = None


class Key(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str | None = None
    name: str | None = None
    credit_limit: float | None = None
    credits_used_month: float | None = None


class KnowledgeGraph(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    title: str | None = None
    type: str | None = None
    website: str | None = None
    image_url: str | None = None
    description: str | None = None
    description_source: str | None = None
    description_link: str | None = None
    attributes: dict[str, str] | None = None


class LensRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    url: AnyUrl
    """
    Image URL
    """
    country: str | None = None
    language: str | None = None
    format: str | None = None
    fields: str | None = None
    max_age: int | None = None


class LensResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    results: list[LensResult]
    meta: Meta


class LensResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    position: int
    title: str
    source: str | None = None
    link: str
    domain: str | None = None
    image_url: str | None = None
    thumbnail_url: str | None = None


class Match(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    position: int
    title: str
    link: str


class Meta(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request_id: str
    credits_used: float
    engine: Annotated[str | None, Field(examples=["google", "brave", "consensus", "stub"])] = None
    """
    The provider that produced the result (`consensus` for a merged engine=consensus answer)
    """
    route: list[RouteStep] | None = None
    """
    Provider attempts in order (fresh results only; absent on cache hits). With engine=consensus, every provider started; ones stopped early are `canceled`, ones cut off by the deadline `timeout`
    """
    cached: bool
    cached_at: AwareDatetime | None = None
    resolved_urls: bool | None = None
    parse_quality: str | None = None
    latency_ms: int | None = None


class Month(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    credits: float
    requests: int


class NewsResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    results: list[NewsResult]
    meta: Meta


class NewsResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    position: int
    title: str
    link: str
    domain: str | None = None
    snippet: str | None = None
    date: str | None = None
    source: str | None = None
    image_url: str | None = None


class OrganicResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    position: int
    title: str
    link: str
    """
    Resolved destination URL (never a google.com/url or /goto redirect)
    """
    domain: str
    """
    Canonical host without www.
    """
    displayed_link: str | None = None
    snippet: str | None = None
    date: str | None = None
    sitelinks: list[Sitelink] | None = None
    attributes: dict[str, str] | None = None
    rating: float | None = None
    rating_count: int | None = None
    content: str | None = None
    """
    Page Markdown when include_content covered this result
    """
    sources: Annotated[list[str] | None, Field(examples=[["google", "brave", "bing"]])] = None
    """
    engine=consensus only. The providers that returned this result, in route order; results are ranked by how many there are
    """


class PageMetadata(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    title: str | None = None
    description: str | None = None
    language: str | None = None
    canonical: str | None = None
    site_name: str | None = None
    image: str | None = None
    published_time: str | None = None
    author: str | None = None


class PatentResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    position: int
    title: str
    snippet: str | None = None
    link: str
    publication_number: str | None = None
    priority_date: str | None = None
    filing_date: str | None = None
    grant_date: str | None = None
    publication_date: str | None = None
    inventor: str | None = None
    assignee: str | None = None
    language: str | None = None
    pdf_url: str | None = None
    thumbnail_url: str | None = None


class PatentsResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    results: list[PatentResult]
    meta: Meta


class PeopleAlsoAsk(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    question: str
    snippet: str | None = None
    title: str | None = None
    link: str | None = None


class PlaceResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    position: int
    title: str
    address: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    rating: float | None = None
    rating_count: int | None = None
    price_level: str | None = None
    type: str | None = None
    types: list[str] | None = None
    website: str | None = None
    phone_number: str | None = None
    opening_hours: dict[str, str] | None = None
    thumbnail_url: str | None = None
    place_id: str | None = None
    cid: str | None = None
    fid: str | None = None


class PlacesResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    results: list[PlaceResult]
    meta: Meta


class RankRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    q: str
    domain: str
    """
    Domain to find, e.g. "example.com" (subdomains match)
    """
    num: int | None = 100
    country: str | None = None
    language: str | None = None
    location: str | None = None
    device: str | None = None
    max_age: int | None = None


class RankResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    domain: str
    position: int | None
    """
    Best organic position
    """
    matches: list[Match]
    checked: int
    """
    Organic results inspected
    """
    meta: Meta


class RelatedSearch(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    query: str


class RequestEcho(BaseModel):
    """
    The normalised request that produced this response (defaults filled in)
    """

    model_config = ConfigDict(
        extra="allow",
    )
    endpoint: Annotated[str, Field(examples=["search", "news", "lens"])]
    engine: str | list[str]
    """
    The engine policy as asked (google, auto, one provider or a list)
    """
    q: str | None = None
    url: str | None = None
    country: str | None = None
    language: str | None = None
    location: str | None = None
    num: int | None = None
    page: int | None = None
    device: str | None = None
    autocorrect: bool | None = None
    tbs: str | None = None
    safe: str | None = None
    place_id: str | None = None
    cid: str | None = None
    fid: str | None = None
    sort: str | None = None
    include_content: int | None = None
    format: str | None = None


class Response(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    snippet: str | None = None
    date: str | None = None


class ReviewResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    rating: float | None = None
    date: str | None = None
    iso_date: str | None = None
    snippet: str | None = None
    likes: int | None = None
    user: User | None = None
    response: Response | None = None


class ReviewsRequest(BaseModel):
    """
    One of place_id, cid or fid is required
    """

    model_config = ConfigDict(
        extra="allow",
    )
    place_id: str | None = None
    cid: str | None = None
    fid: str | None = None
    country: str | None = None
    language: str | None = None
    sort: str | None = "most_relevant"
    page_token: str | None = None
    """
    `next_page_token` from the previous page, unchanged. Opaque and bound to the place and `sort` it was issued for (anything else is a 400). Paging reaches the first 100 reviews of a place per sort order.
    """
    num: Annotated[int | None, Field(le=50)] = 10
    """
    Reviews per page (a page can be shorter when Google stops loading early; `next_page_token` then resumes after it)
    """
    format: str | None = None
    fields: str | None = None
    max_age: int | None = None


class ReviewsResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    results: list[ReviewResult]
    next_page_token: str | None = None
    """
    Pass as `page_token` for the next page. Absent on the last page and at the 100-review depth limit
    """
    meta: Meta


class RouteStep(BaseModel):
    """
    One provider attempt behind this answer. Proxy pools are internal and never listed.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    provider: Annotated[str, Field(examples=["google", "brave"])]
    outcome: str
    ms: int
    """
    Duration of the attempt in milliseconds
    """


class ScholarResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    results: list[ScholarResult]
    meta: Meta


class ScholarResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    position: int
    title: str
    link: str
    domain: str | None = None
    publication_info: str | None = None
    snippet: str | None = None
    year: int | None = None
    cited_by: int | None = None
    pdf_url: str | None = None
    id: str | None = None


class SearchInformation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    searchTime: float | None = None
    formattedSearchTime: str | None = None
    totalResults: str | None = None
    formattedTotalResults: str | None = None


class SearchRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    q: Annotated[str, Field(max_length=2048, min_length=1)]
    country: str | None = "us"
    """
    Country code (ISO 3166-1 alpha-2)
    """
    language: str | None = "en"
    """
    Interface language (e.g. en
    """
    location: str | None = None
    """
    Free-text location, e.g. "Austin, Texas, United States"
    """
    uule: str | None = None
    """
    Pre-encoded Google location (overrides location)
    """
    ll: str | None = None
    """
    Maps viewport "@lat,lng,14z" (maps only)
    """
    num: int | None = 10
    """
    10, or up to 100 for the depth bundle on search and news (7 credits for 100; values between round up to whole pages). Other verticals return one page of 10
    """
    page: Annotated[int | None, Field(ge=1, le=10)] = 1
    time: str | None = None
    """
    Only results from the last hour/day/…
    """
    tbs: str | None = None
    """
    Advanced: raw Google tbs filter (e.g. qdr:d); overrides time
    """
    device: str | None = "desktop"
    safe: str | None = "off"
    autocorrect: bool | None = True
    format: str | None = "json"
    fields: str | None = None
    """
    Comma-separated projection, e.g. "results.title,results.link,knowledge_graph"
    """
    include_content: Annotated[int | None, Field(ge=0, le=5)] = 0
    """
    Also fetch the top N organic pages as Markdown (+1 credit each fetched page)
    """
    ads: bool | None = False
    """
    Include sponsored results
    """
    max_age: Annotated[int | None, Field(ge=0)] = None
    """
    Accept a cached result up to this many seconds old (50% of credits on a hit)
    """
    engine: str | EngineParam1 | None = None
    """
    Which search providers may answer. `google` (the default) is Google only; within Google, SerpKite always fails over across its own proxy pools. `auto` allows falling back to other enabled providers, in route order, when Google is blocked or times out. A single other provider (`brave`) or a list (`["google","brave"]`, or `google,brave` in a query string) restricts the request to those providers. `meta.engine` always names the provider that answered and credits follow that provider's price. A key with "Allow fallback to other search engines" on treats a request without `engine` as `auto`. `consensus` (`/v1/search` only; 400 elsewhere, and it can't be combined with other names) queries several independent search indexes in parallel (at most one Bing-backed provider, so Yahoo or DuckDuckGo never count as agreeing with Bing), merges the results by URL and ranks them by how many providers returned each one. Each result lists its `sources`; `meta.engine` is `consensus` and `meta.route` lists every provider attempt. It stops once `num` unique results are in hand or after a few seconds, and costs the sum of one page at each provider that returned results (providers that failed, came back empty or were never started are free).
    """


class SearchResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    results: list[OrganicResult]
    answer_box: AnswerBox | None = None
    knowledge_graph: KnowledgeGraph | None = None
    ads: list[OrganicResult] | None = None
    people_also_ask: list[PeopleAlsoAsk] | None = None
    related_searches: list[RelatedSearch]
    top_stories: list[NewsResult] | None = None
    places: list[PlaceResult] | None = None
    meta: Meta


class ShoppingResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    results: list[ShoppingResult]
    meta: Meta


class ShoppingResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    position: int
    title: str
    source: str | None = None
    link: str | None = None
    price: str | None = None
    price_value: float | None = None
    currency: str | None = None
    delivery: str | None = None
    image_url: str | None = None
    rating: float | None = None
    rating_count: int | None = None
    offers: str | None = None
    product_id: str | None = None


class Sitelink(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    title: str
    link: str
    snippet: str | None = None


class Status(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    status: str
    window_minutes: int
    updated_at: AwareDatetime
    endpoints: list[Endpoint]


class Suggestion(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    value: str


class User(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = None
    thumbnail: str | None = None
    reviews: int | None = None


class VideoResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    position: int
    title: str
    link: str
    domain: str | None = None
    snippet: str | None = None
    image_url: str | None = None
    duration: str | None = None
    source: str | None = None
    channel: str | None = None
    date: str | None = None


class VideosResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    results: list[VideoResult]
    meta: Meta


class WebpageRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    url: AnyUrl
    format: str | None = "json"
    include_html: bool | None = False
    max_age: int | None = None


class WebpageResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    request: RequestEcho
    url: str
    """
    Final URL after redirects
    """
    status_code: int | None = None
    markdown: str
    text: str | None = None
    html: str | None = None
    """
    Only with include_html=true
    """
    metadata: PageMetadata
    meta: Meta
