#!/usr/bin/env bash
# Regenerates src/serpkite/_models.py from the OpenAPI contract (backend/api/serp-api.yaml).
# Usage (from sdks/python): ./scripts/gen_models.sh
set -euo pipefail
cd "$(dirname "$0")/.."

# The monorepo contract, or the copy the mirror bundles into the public
# serpkite-python repo (scripts/sdk-mirror.sh in the monorepo).
SPEC="../../backend/api/serp-api.yaml"
[ -f "$SPEC" ] || SPEC="openapi/serp-api.yaml"
OUT="src/serpkite/_models.py"

uv run datamodel-codegen \
  --input "$SPEC" \
  --input-file-type openapi \
  --openapi-scopes schemas \
  --output "$OUT" \
  --output-model-type pydantic_v2.BaseModel \
  --target-python-version 3.10 \
  --use-standard-collections \
  --use-annotated \
  --field-constraints \
  --use-schema-description \
  --use-field-description \
  --use-double-quotes \
  --extra-fields allow \
  --ignore-enum-constraints \
  --collapse-root-models \
  --reuse-model \
  --keep-model-order \
  --disable-timestamp \
  --formatters ruff-format \
  --custom-file-header "# Generated by scripts/gen_models.sh from backend/api/serp-api.yaml. Do not edit by hand."

echo "wrote $OUT"
